id: "predict"
name: "Predict"
version: "0.3.0"
description: "Run inference with a trained centroid model."
category_path: "neural/processors"
entrypoint:
  file: "wrapper.py"
  callable: "main"
environment:
  python: ">=3.11,<3.13"
  pip:
    - "numpy>=1.26"
inputs:
  model:
    type: "model"
  x:
    type: "embedding"
params:
  threshold:
    type: "number"
    default: 0.5
    ui: { label: "Threshold" }
outputs:
  pred:
    type: "predictions"
execution:
  deterministic: true
  cacheable: false
side_effects:
  network: "none"
  disk: "read_only"
  subprocess: "forbidden"
resources:
  gpu: "forbidden"
  threads: 1


