id: "saw.example.bandpass"
name: "Bandpass Filter"
version: "0.1.0"
description: "Bandpass filter an ndarray signal."
entrypoint:
  file: "wrapper.py"
  callable: "main"
environment:
  python: ">=3.11,<3.13"
  pip:
    - "numpy>=1.26"
inputs:
  x:
    type: "ndarray"
    dtype: "float32"
    shape: ["channels", "samples"]
params:
  low_hz:
    type: "number"
    default: 300
    ui: { label: "Low (Hz)" }
  high_hz:
    type: "number"
    default: 6000
    ui: { label: "High (Hz)" }
  fs_hz:
    type: "number"
    default: 30000
    ui: { label: "Sampling rate (Hz)" }
outputs:
  y:
    type: "ndarray"
    dtype: "float32"
    shape: ["channels", "samples"]
execution:
  deterministic: true
  cacheable: true
side_effects:
  network: "none"
  disk: "read_only"
  subprocess: "forbidden"
resources:
  gpu: "forbidden"
  threads: 2


